version: "3.1"
#  Removing ports as they wont be needed on CI
services:
  web:
    image: "my-registry:55000/gen:pluralsight-admin-web-image-ci-${BUILD_NUMBER-10}"
    #build:
    #  context: ./Pluralsight-Admin-Web
    #  dockerfile: ./.docker/node.development.web.dockerfile
    ports:
      - "${WEB_PORT_GENERATOR-8080}:80"
  api:
    image: "my-registry:55000/gen:pluralsight-admin-api-image-ci-${API_BUILD_NUMBER-10}"
    #build:
    #  context: ./Pluralsight-Admin-Api
    #  dockerfile: ./.docker/node.development.api.dockerfile
    ports:
      - "${API_PORT_GENERATOR-3001}:3001"
