version: "3.7"

services:
  viz:
    image: dockersamples/visualizer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8090:8080"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    #environment:
    #  - HOST=localhost
